- name: Puxar imagem mais recente do Docker Hub
  docker_container:
    name: nginx
    image: caza6367/nginx-devops:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    recreate: yes
