- name: Atualizar sistema
  raw: sudo yum update -y
  changed_when: false

- name: Instalar Docker
  raw: sudo yum install -y docker
  changed_when: false

- name: Iniciar Docker
  raw: sudo systemctl start docker
  changed_when: false

- name: Habilitar Docker no boot
  raw: sudo systemctl enable docker
  changed_when: false

- name: Adicionar ec2-user ao grupo docker
  raw: sudo usermod -aG docker ec2-user
  changed_when: false
