- name: Instalar Docker
  raw: |
    yum install -y docker

- name: Iniciar Docker
  raw: |
    systemctl enable docker
    systemctl start docker

- name: Adicionar ec2-user ao grupo docker
  raw: |
    usermod -aG docker ec2-user

- name: Instalar pip
  raw: |
    yum install -y python3-pip

- name: Instalar Docker SDK
  raw: |
    pip3 install docker
