- name: Instalar Docker
  yum:
    name: docker
    state: present

- name: Iniciar Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Adicionar ec2-user ao grupo docker
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Instalar python3-pip
  yum:
    name: python3-pip
    state: present

- name: Instalar Docker SDK para Python
  pip:
    name: docker
    executable: pip3
