- name: Bootstrap Python
  hosts: ec2
  become: true
  gather_facts: false
  tasks:
    - name: Garantir Python3 instalado
      raw: |
        sudo yum install -y python3
      changed_when: false

- name: Configurar EC2
  hosts: ec2
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - docker
